server:
  port: 8080

spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/spring
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  boot:
    admin:
      client:
        url: http://localhost:8080



  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug


management:
  endpoints:
    web:
      exposure:
        include: "*"
      #        include: health, metrics

      base-path: "/monitoring"

  endpoint:
    health:
      #      enabled: true
      #      show-details: always
      group:
        custom:
          include: diskSpace, ping
          show-components: always
          show-details: always
