jwt:
  secret: VEVTVCBTRUNSRVQgS0VZVEVTVCBTRUNSRVQgS0VZVEVTVCBTRUNSRVQgS0VZVEVTVCBTRUNSRVQgS0VZVEVTVCBTRUNSRVQgS0VZ

spring:
  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:h2:tcp://localhost/~/spring
#    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  redis:
    host: 127.0.0.1
    port: 6379

