server:
  port: 8080

spring:
  profiles:
    active: local

#  security 설정
  security:
    user:
      name: "admin"
      password: "pass"
      roles: "ADMIN"


  boot:
    admin:
      client:
        url: http://localhost:8080

    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK

management:
  endpoints:
    web:
      exposure:
        include: "*"
      #        include: health, metrics

      base-path: "/admin/monitoring"

  endpoint:
    health:
      #      enabled: true
      #      show-details: always
      group:
        custom:
          include: diskSpace, ping
          show-components: always
          show-details: always
