jwt:
  secret: testKey
  time: 60000 # 1분

spring:
  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    #    url: jdbc:h2:tcp://localhost/~/spring
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

