server:
  port: 8080

spring:
  # multipart 용량 설정
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
  profiles:
    active: local

#  security 설정
#  security:
#    user:
#      name: "admin"
#      password: "pass"
#      roles: "ADMIN"

  boot:
    admin:
      client:
        url: http://127.0.0.1:8090

    properties:
      hibernate:
        show_sql: true
        format_sql: true

  redis:
    lettuce:
      pool:
        max-active: 10


logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secretKey: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
  algorithm: HS512

coolsms:
  devHee:
    apiKey: NCSVJBMVYB7TOOQV

management:
  server:
    port: 8001
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/monitoring"

  endpoint:
    health:
      group:
        custom:
          include: "*"
          show-components: always
          show-details: always