server:
  port: 8080

spring:
  profiles:
    active: local

  boot:
    admin:
      client:
        url: http://localhost:8080

    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug


management:
  endpoints:
    web:
      exposure:
        include: "*"
      #        include: health, metrics

      base-path: "/monitoring"

  endpoint:
    health:
      #      enabled: true
      #      show-details: always
      group:
        custom:
          include: diskSpace, ping
          show-components: always
          show-details: always
